apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bungeecord.fullname" . }}
  labels:
    {{- include "bungeecord.labels" . | nindent 4 }}
type: Opaque
data:
  sftp-config: {{ printf "{\"Global\":{\"Chroot\":{\"Directory\":\"%s\",\"StartPath\":\"sftp\"}, \"Directories\": [\"sftp\"]}, \"Users\": [{\"Username\": \"minecraft\", \"Password\": \"%s\"}]}" "%h" .Values.sftp.password | b64enc }}
