apiVersion: v1
kind: Service
metadata:
  name: {{ include "bungeecord.fullname" . }}
  labels:
    {{- include "bungeecord.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: bungeecord
      protocol: TCP
      name: bungeecord
  selector:
    {{- include "bungeecord.selectorLabels" . | nindent 4 }}
