apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio.fullname" . }}-rcon
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rconService.type }}
  ports:
    - port: {{ .Values.rconService.port }}
      targetPort: rcon
      protocol: TCP
      name: rcon
  selector:
    {{- include "factorio.selectorLabels" . | nindent 4 }}
