{{- if .Values.sftp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}-sftp
  labels:
    {{- include "minecraft.labelsSftp" . | nindent 4 }}
  annotations:
{{ toYaml .Values.sftp.service.annotations | indent 4 }}
spec:
  type: {{ .Values.sftp.service.type }}
  {{- if .Values.sftp.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.sftp.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.sftp.service.port }}
      targetPort: sftp
      protocol: TCP
      name: sftp
  selector:
    {{- if eq .Values.sftp.deploymentType "statefulset" }}
    {{- include "minecraft.selectorLabelsSftp" . | nindent 4 }}
    {{- else }}
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
    {{- end}}
{{- end }}
