{{- if .Values.server.eula }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "minecraft.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minecraft.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minecraft.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "minecraft.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
            - name: rcon
              containerPort: 25575
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: EULA
              value: "{{ .Values.server.eula | toString | upper }}"
            - name: ENABLE_RCON
              value: "{{ .Values.rcon.enabled }}"
            - name: RCON_PASSWORD
              value: "{{ .Values.rcon.password }}"

            # Install process
            - name: BUKKIT_DOWNLOAD_URL
              value: "{{ .Values.server.bukkitDownloadUrl }}"
            - name: PAPER_DOWNLOAD_URL
              value: "{{ .Values.server.paperDownloadUrl }}"
            - name: SPIGOT_DOWNLOAD_URL
              value: "{{ .Values.server.spigotDownloadUrl }}"
            - name: TYPE
              value: "{{ .Values.server.type }}"
            - name: VERSION
              value: "{{ .Values.server.version }}"

            # Process
            - name: CONSOLE
              value: 'false'
            - name: GUI
              value: 'false'

            # server.properties
            - name: DIFFICULTY
              value: "{{ .Values.server.difficulty }}"
            - name: GENERATE_STRUCTURES
              value: "{{ .Values.server.generateStructures }}"
            - name: MAX_PLAYERS
              value: "{{ .Values.server.maxPlayers }}"
            - name: MODE
              value: "{{ .Values.server.gameMode }}"
            - name: MOTD
              value: "{{ .Values.server.motd }}"
            - name: OPS
              value: "{{ .Values.server.ops }}"
            - name: SPAWN_ANIMALES
              value: "{{ .Values.server.spawnAnimals }}"
            - name: SPAWN_MONSTERS
              value: "{{ .Values.server.spawnMonsters }}"
            - name: SPAWN_NPCs
              value: "{{ .Values.server.spawnNPCs }}"
            - name: VIEW_DISTANCE
              value: "{{ .Values.server.viewDistance }}"

            # JVM
            - name: JVM_XX_OPTS
              value: "{{ .Values.server.jvmXXOpts }}"
            - name: MEMORY
              value: "{{ .Values.server.memory }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "minecraft.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{ end }}
{{ end }}
