replicaCount: 1

image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
securityContext: {}

service:
  annotations: {}
  type: ClusterIP
  port: 25565

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

startupProbe:
  exec:
    command:
      - mc-monitor
      - status
  failureThreshold: 10
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

livenessProbe:
  exec:
    command:
      - mc-monitor
      - status
  failureThreshold: 10
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

readinessProbe:
  exec:
    command:
      - mc-monitor
      - status
  failureThreshold: 300
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

server:
  eula: false

  # Install process
  bukkitDownloadUrl: ''
  paperDownloadUrl: ''
  spigotDownloadUrl: ''
  type: VANILLA
  version: 1.15.2

  # server.properties
  difficulty: easy
  gameMode: survival
  generateStructures: true
  maxPlayers: 20
  motd: A Minecraft Server
  onlineMode: true
  ops: ''
  spawnAnimals: true
  spawnMonsters: true
  spawnNPCs: true
  viewDistance: 10

  # JVM
  jvmXXOpts: '-XX:+UseG1GC'
  memory: 512M
  useAikarFlags: true
  useLargePages: true

rcon:
  enabled: true
  password: 1234

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi

sftp:
  enabled: false
  deploymentType: container
  image:
    repository: emberstack/sftp
    pullPolicy: IfNotPresent
    tag: latest
  password: changeme

  service:
    annotations: {}
    type: ClusterIP
    port: 22
